# SPDX-License-Identifier: BSD-3-Clause-Clear
obj-$(CPTCFG_ATH12K) += ath12k_wifi8.o
ath12k_wifi8-y += core.o \
		  mgmt_rx.o \
	          pci.o \
		  hw.o \
		  mhi.o \
		  ce.o \
		  wmi.o \
		  dp.o \
		  dp_tx.o \
		  dp_rx.o \
		  hal.o \
		  hal_tx.o \
		  hal_rx.o \
		  hal_qcn9625.o\
		  dp_peer.o\
		  dp_ast.o \
		  dp_tx_flow_info.o \
		  dp_htt.o \
		  hal_queue.o \
		  dp_pool.o \
		  dp_msdu_queue.o \
		  dp_tx_tid.o \
		  dp_tx_queue.o
